# Generated by Django 4.2.4 on 2023-11-17 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_data', models.JSONField()),
                ('processed_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
